pub mod c;
pub mod c_handshake;
pub mod c_runtime;
pub mod cpp;
pub mod cpp_handshake;
pub mod cpp_runtime;
pub mod csharp;
pub mod csharp_handshake;
pub mod csharp_runtime;
pub mod go;
pub mod go_handshake;
pub mod go_runtime;
pub mod handshake;
pub mod javascript;
pub mod javascript_handshake;
pub mod javascript_runtime;
pub mod net_schema;
pub mod rust;
pub mod rust_runtime;
pub mod typescript;
pub mod typescript_handshake;
pub mod typescript_runtime;

use crate::ir::WireType;
use crate::model::pascal_case;
use crate::timestamp;

pub fn codec_type_name(model: &str, codec: &str) -> String {
    format!("{model}{}Codec", pascal_case(codec))
}

pub fn spelled_types<'a>(ty: &'a WireType, into: &mut std::collections::BTreeSet<&'a str>) {
    if let WireType::Array(element) = ty {
        match element.as_ref() {
            WireType::Model(name) => {
                into.insert(name);
            }
            nested @ WireType::Array(_) => spelled_types(nested, into),
            _ => {}
        }
    }
}

pub const MARKER: &str = "// GENERATED BY fomoxac";

pub const TIMESTAMP_PREFIX: &str = "// generated-at: ";

fn timestamp_prefix(line: &str) -> Option<&'static str> {
    if line.starts_with(TIMESTAMP_PREFIX) {
        Some(TIMESTAMP_PREFIX)
    } else {
        None
    }
}

pub const MODULE_ROOT: &str = "mod.rs";

pub const FILE_ATTRIBUTES: &str = "#![allow(dead_code, unused_imports)]\n\n";

#[derive(Default)]
pub struct Header<'a> {
    pub source: Option<&'a str>,
    pub model: Option<&'a str>,
    pub codec: Option<&'a str>,
    pub fingerprint: Option<String>,
    pub note: Option<&'a str>,
}

impl Header<'_> {
    pub fn render(&self) -> String {
        let mut out = String::with_capacity(512);
        out.push_str(MARKER);
        out.push('\n');
        out.push_str("// DO NOT EDIT MANUALLY\n");
        if let Some(source) = self.source {
            out.push_str(&format!("// source: {source}\n"));
        }
        if let Some(model) = self.model {
            out.push_str(&format!("// model: {model}\n"));
        }
        if let Some(codec) = self.codec {
            out.push_str(&format!("// codec: {codec}\n"));
        }
        if let Some(fingerprint) = &self.fingerprint {
            out.push_str(&format!("// fingerprint: {fingerprint}\n"));
        }
        out.push_str(&format!(
            "// fomoxac-version: {}\n",
            env!("CARGO_PKG_VERSION")
        ));
        out.push_str(TIMESTAMP_PREFIX);
        out.push_str(&timestamp::now_utc());
        out.push('\n');
        if let Some(note) = self.note {
            out.push_str("//\n");
            for line in note.lines() {
                if line.is_empty() {
                    out.push_str("//\n");
                } else {
                    out.push_str(&format!("// {line}\n"));
                }
            }
        }
        out.push('\n');
        out
    }
}

pub fn same_but_for_timestamp(left: &str, right: &str) -> bool {
    let mut left = left.lines();
    let mut right = right.lines();

    loop {
        match (left.next(), right.next()) {
            (None, None) => return true,
            (Some(one), Some(other)) => {
                if one == other {
                    continue;
                }
                let one_prefix = timestamp_prefix(one);
                if one_prefix.is_some() && one_prefix == timestamp_prefix(other) {
                    continue;
                }
                return false;
            }
            _ => return false,
        }
    }
}

pub fn without_timestamp(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for line in text.lines() {
        match timestamp_prefix(line) {
            Some(prefix) => out.push_str(prefix),
            None => out.push_str(line),
        }
        out.push('\n');
    }
    out
}

pub fn module_root(modules: &[String], codecs: &[(String, String)], net_schema: bool) -> String {
    let mut out = Header {
        note: Some(
            "The generated module tree. Mount it the ordinary way - from src/, this\n\
             is `mod generated;` - and everything below is reachable through it:\n\
             \n\
                 mod generated;\n\
                 use generated::{PlayerEdgeCodec, Reader, Writer};\n\
             \n\
             Nothing to add to Cargo.toml and nothing to import from elsewhere: the\n\
             Fomoxa runtime is the `runtime` module beside this file.",
        ),
        ..Header::default()
    }
    .render();
    out.push_str(FILE_ATTRIBUTES);

    for module in modules {
        out.push_str(&format!("pub mod {module};\n"));
    }

    out.push_str("\n// Re-exported so that a codec can be named without knowing which file it\n");
    out.push_str("// landed in.\n");
    out.push_str("pub use self::handshake::*;\n");
    if net_schema {
        out.push_str(&format!("pub use self::{}::*;\n", net_schema::RUST_MODULE));
    }
    out.push_str("pub use self::runtime::{DecodeError, Limits, Reader, Writer};\n");
    for (module, codec) in codecs {
        out.push_str(&format!("pub use self::{module}::{codec};\n"));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::{module_root, same_but_for_timestamp, Header, MARKER};

    #[test]
    fn a_header_carries_what_the_file_is() {
        let header = Header {
            source: Some("src/models/player.rs"),
            model: Some("Player"),
            codec: Some("edge"),
            fingerprint: Some("sha256:abc".to_owned()),
            note: None,
        }
        .render();

        assert!(header.starts_with(MARKER), "{header}");
        assert!(header.contains("// DO NOT EDIT MANUALLY\n"));
        assert!(header.contains("// source: src/models/player.rs\n"));
        assert!(header.contains("// model: Player\n"));
        assert!(header.contains("// codec: edge\n"));
        assert!(header.contains("// fingerprint: sha256:abc\n"));
        assert!(header.contains("// fomoxac-version: "));
        assert!(header.contains("// generated-at: "));
    }

    #[test]
    fn only_the_timestamp_line_is_allowed_to_differ() {
        let one = "// a\n// generated-at: 2026-01-01T00:00:00Z\n// b\n";
        let same = "// a\n// generated-at: 2030-06-06T12:00:00Z\n// b\n";
        let different = "// a\n// generated-at: 2030-06-06T12:00:00Z\n// c\n";

        assert!(same_but_for_timestamp(one, same));
        assert!(!same_but_for_timestamp(one, different));
        assert!(!same_but_for_timestamp(one, "// a\n"));
    }

    #[test]
    fn the_root_declares_every_module_and_re_exports_the_codecs() {
        let text = module_root(
            &[
                "runtime".to_owned(),
                "handshake".to_owned(),
                "player_edge".to_owned(),
            ],
            &[("player_edge".to_owned(), "PlayerEdgeCodec".to_owned())],
            false,
        );

        assert!(text.contains("pub mod runtime;\n"), "{text}");
        assert!(text.contains("pub mod handshake;\n"), "{text}");
        assert!(text.contains("pub mod player_edge;\n"), "{text}");
        assert!(
            text.contains("pub use self::runtime::{DecodeError, Limits, Reader, Writer};\n"),
            "{text}"
        );
        assert!(
            text.contains("pub use self::player_edge::PlayerEdgeCodec;\n"),
            "{text}"
        );
        assert!(!text.contains("include!"), "{text}");
        assert!(!text.contains("net_schema"), "{text}");
    }

    #[test]
    fn the_root_re_exports_the_net_schema_when_asked() {
        let text = module_root(
            &[
                "runtime".to_owned(),
                "handshake".to_owned(),
                "net_schema".to_owned(),
            ],
            &[],
            true,
        );

        assert!(text.contains("pub mod net_schema;\n"), "{text}");
        assert!(text.contains("pub use self::net_schema::*;\n"), "{text}");
    }
}
